# Generated by Django 2.0.2 on 2018-02-04 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RiskFormField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField()),
                ('label', models.CharField(max_length=200)),
                ('field_type', models.CharField(choices=[('TEXT', 'TEXT'), ('NUMBER', 'NUMBER'), ('DATE', 'DATE'), ('OPTIONS', 'OPTIONS')], default='TEXT', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RiskFormFieldOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField()),
                ('text', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RiskType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField()),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'in_risk',
            },
        ),
        migrations.AddField(
            model_name='riskformfield',
            name='risk_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='risk.RiskType'),
        ),
    ]
