# Generated by Django 2.0.2 on 2018-02-07 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='riskformfield',
            table='risk_form_field',
        ),
    ]
