# Generated by Django 2.0.2 on 2018-02-07 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0002_auto_20180207_0156'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='riskformfieldoption',
            table='risk_form_field_option',
        ),
        migrations.AlterModelTable(
            name='risktype',
            table='risk',
        ),
    ]
