# Generated by Django 2.0.2 on 2018-02-07 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0003_auto_20180207_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risktype',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
