# Generated by Django 2.0.2 on 2018-02-07 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0004_auto_20180207_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskformfield',
            name='date_modified',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='riskformfieldoption',
            name='date_modified',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='risktype',
            name='date_modified',
            field=models.DateTimeField(null=True),
        ),
    ]
