# Generated by Django 2.0.2 on 2018-02-08 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0006_auto_20180208_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskformfieldoption',
            name='form_field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='risk.RiskFormField'),
        ),
    ]
