# Generated by Django 2.0.2 on 2018-02-08 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0007_riskformfieldoption_form_field'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='risktype',
            table='risk_type',
        ),
    ]
