# Generated by Django 2.0.2 on 2018-02-09 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0008_auto_20180208_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskformfieldoption',
            name='form_field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='options', to='risk.RiskFormField'),
        ),
    ]
